name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: '3.13'
          enable-cache: true
          cache-suffix: ${{ github.job }}
      - run: uv sync --locked
      - run: make lint

  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: ${{ github.job }}
      - run: uv sync --locked
      - run: make test
