name: Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pipenv'
      - run: make .ci-setup-env
      - run: make upload-to-pypi
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

